"""
Evaluation baselines for comparing different rule extraction methods.

Implements multiple approaches to mining access control rules:
1. Naive frequency-based (most accessed resources)
2. Trie-based (current system)

Compares them on metrics like precision, recall, f1-score.
"""

from collections import defaultdict, Counter
from .baseline_engine import matches_pattern, evaluate_request as trie_evaluate_request


class NaiveBaseline:
    """
    Naive frequency-based baseline.
    
    Approach: For each user/action pair, rules are simply the top-K 
    most frequently accessed resources.
    
    This serves as a simpler comparison point to show the value of pattern extraction.
    """
    
    def __init__(self, top_k=3):
        self.top_k = top_k
    
    def mine_rules(self, logs):
        """
        Extract rules using frequency alone.
        
        For each (userId, action) pair, keep the top-K most accessed resources.
        """
        grouped = defaultdict(list)
        
        for log in logs:
            grouped[(log['userId'], log['action'])].append(log)
        
        rules = []
        
        for (uid, action), log_list in grouped.items():
            # Count frequency of each resource
            resource_counts = Counter(log['resource'] for log in log_list)
            
            # Get top-K resources
            for resource, count in resource_counts.most_common(self.top_k):
                confidence = count / len(log_list)
                rules.append({
                    'userId': uid,
                    'action': action,
                    'resourcePattern': resource,  # No parameterization
                    'support': count,
                    'confidence': round(confidence, 2),
                    'type': 'naive'
                })
        
        return rules
    
    def evaluate_request(self, user_id, resource, action, rules):
        """Check if request matches any naive rule."""
        for r in rules:
            if (r['userId'] == user_id and 
                r['action'] == action and
                r['resourcePattern'] == resource):  # Exact match only
                return 'allowed'
        
        return 'over-granted'


def compare_baselines(logs):
    """
    Compare naive vs Trie-based baselines on test data.
    
    Returns breakdown of how each method performs.
    """
    from .baseline_engine import mine_coarse_rules, refine_rules
    
    # Split data
    import random
    random.shuffle(logs)
    split = int(len(logs) * 0.7)
    train_logs = logs[:split]
    test_logs = logs[split:]
    
    # Filter to allowed logs for baseline training
    baseline_logs = [
        log for log in train_logs
        if log.get('label') == 'allowed' or 'label' not in log
    ]
    
    # Train both baselines
    naive = NaiveBaseline(top_k=3)
    naive_rules = naive.mine_rules(baseline_logs)
    
    trie_coarse = mine_coarse_rules(baseline_logs)
    trie_rules = refine_rules(trie_coarse)
    
    # Evaluate both on test set
    naive_metrics = evaluate_baseline(test_logs, naive_rules, naive.evaluate_request)
    trie_metrics = evaluate_baseline(test_logs, trie_rules, trie_evaluate_request)
    
    return {
        'naive': {
            **naive_metrics,
            'rules_count': len(naive_rules),
            'method': 'Frequency-based (Top-K)'
        },
        'trie': {
            **trie_metrics,
            'rules_count': len(trie_rules),
            'method': 'Pattern-based (Trie)'
        }
    }


def evaluate_baseline(test_logs, rules, evaluate_func):
    """
    Evaluate a baseline method on test logs.
    
    Args:
        test_logs: List of test logs with labels
        rules: Rules generated by the baseline
        evaluate_func: Function(userId, resource, action, rules) -> verdict
        
    Returns:
        Dict with TP, FP, FN, TN, precision, recall, f1_score
    """
    TP = FP = FN = TN = 0
    
    for log in test_logs:
        # Skip logs without labels
        if 'label' not in log:
            continue
        
        pred = evaluate_func(log['userId'], log['resource'], log['action'], rules)
        actual = log['label']
        
        if pred == 'over-granted' and actual == 'over-granted':
            TP += 1
        elif pred == 'over-granted' and actual == 'allowed':
            FP += 1
        elif pred == 'allowed' and actual == 'over-granted':
            FN += 1
        else:
            TN += 1
    
    precision = TP / max((TP + FP), 1)
    recall = TP / max((TP + FN), 1)
    f1 = 2 * precision * recall / max((precision + recall), 1)
    
    return {
        'tp': TP,
        'fp': FP,
        'fn': FN,
        'tn': TN,
        'precision': round(precision, 3),
        'recall': round(recall, 3),
        'f1_score': round(f1, 3)
    }
